### ISSUE TITLE
klient: panic after startup

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#10076]
Happened on klient startup right after kd install.

Built from current master (8ebafd046af8cde78f7ef89269fe1d6c719de95c).

```
2016-12-20 19:11:28 [klient] INFO     [remote][restoreMounts queue] Remounted successfully.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x23821c]

goroutine 13 [running]:
panic(0xd4a700, 0xc42000c0e0)
	/Users/rjeczalik/go/src/runtime/panic.go:500 +0x1a1
koding/klient/machine.(*AddrBook).Latest(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klient/machine/addr.go:123 +0x6c
koding/klient/machine/machinegroup/addresses.(*Addresses).Latest(0xc42037d560, 0xc42037d620, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klient/machine/machinegroup/addresses/addresses.go:58 +0x128
koding/klient/machine/machinegroup/addresses.(*Cached).Latest(0xc42037d580, 0xc42037d620, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klient/machine/machinegroup/addresses/cached.go:62 +0xa6
koding/klient/machine/machinegroup.(*Group).dynamicAddr.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420486f18, ...)
	/Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klient/machine/machinegroup/machinegroup.go:175 +0x9f
koding/klient/machine.(*DynamicClient).cron(0xc42012b790)
	/Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klient/machine/dynamic.go:171 +0x197
created by koding/klient/machine.NewDynamicClient
	/Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klient/machine/dynamic.go:104 +0x271
```

**Comment by ppknap** [comment]
I cannot reproduce this, looking on stack-trace - the only possibility that addresses are nil is corrupted database. I will add checks for this.

**Comment by rjeczalik** [comment]
Some debug logs:

```diff
diff --git a/go/src/koding/klient/machine/machinegroup/addresses/cached.go b/go/src/koding/klient/machine/machinegroup/addresses/cached.go
index bacc1f7..9d9b9a4 100644
--- a/go/src/koding/klient/machine/machinegroup/addresses/cached.go
+++ b/go/src/koding/klient/machine/machinegroup/addresses/cached.go
@@ -1,10 +1,12 @@
 package addresses
 
 import (
+       "log"
        "sync"
 
        "koding/klient/machine"
        "koding/klient/storage"
+       "koding/tools/util"
 )
 
 // storageKey is a database key used to store machine addresses.
@@ -29,6 +31,8 @@ func NewCached(st storage.ValueInterface) (*Cached, error) {
                return nil, err
        }
 
+       log.Println("DEBUG", util.LazyJSON(c.addresses.m))
+
        return c, nil
 }
```
```
2016/12/20 22:26:40 DEBUG {
	"5849a2ebca97813764f80894": null,
	"58591b2968795bff132571af": [
		{
			"network": "ip",
			"value": "35.156.250.195",
			"updated_at": "2016-12-20T19:25:46.041112879+01:00"
		},
		{
			"network": "kite",
			"value": "///////27918732-2ed6-46e6-a576-4e4bde08e93d",
			"updated_at": "2016-12-20T19:25:46.041113025+01:00"
		},
		{
			"network": "http",
			"value": "http://35.156.250.195:56789/kite",
			"updated_at": "2016-12-20T19:25:46.041113036+01:00"
		}
	]
}
```

**Comment by rjeczalik** [comment]
No idea though how the db could get corrupted.
