### ISSUE TITLE
server.handlers.invitetoteambycsv should be able to process 500 items at once

### ISSUE THREAD

**Issue by szkl** [koding/koding#10701]
```
  1) server.handlers.invitetoteambycsv should be able to process 500 items at once:
     Uncaught AssertionError: expected [Error: invitation is not found] to not exist
      at servers/lib/server/handlers/invitetoteambycsv.test.coffee:43:27
      at servers/lib/server/handlers/invitetoteambycsv.test.coffee:61:14
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at TCP.onread (net.js:548:20)
```

**Comment by hakankaradis** [comment]
@szkl I couldn't reproduce it in local, try to investigate more

**Comment by szkl** [comment]
It happens in CI builds occasionally.
