### ISSUE TITLE
kd: panic

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#11201]
```
$ kd mount ls
metrics wont be collected:  timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ced75d]

goroutine 1 [running]:
main.run(0xc420010480, 0x3, 0x3)
        /Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klientctl/main.go:1011 +0x8d7d
main.main()
        /Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klientctl/main.go:70 +0x45
```

**Comment by rjeczalik** [comment]
```
$ time kd ls
metrics wont be collected:  timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ced75d]

goroutine 1 [running]:
main.run(0xc42000c320, 0x2, 0x2)
        /Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klientctl/main.go:1011 +0x8d7d
main.main()
        /Users/rjeczalik/src/github.com/koding/koding/go/src/koding/klientctl/main.go:70 +0x45

real    0m5.085s
user    0m0.063s
sys     0m0.027s
(rjeczalik-osxpro.local) {master} ruby-rails-sample $

**Comment by rjeczalik** [comment]
I think I know what's the problem - there's another kd process running:

```
$ ps ax | grep kd
65027 s002  S+     0:00.10 kd ssh purple_watermelon
65029 s002  S+     0:00.15 ssh -i /Users/rjeczalik/.ssh/twoja-stara -o StrictHostKeychecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=300 -o ServerAliveCountMax=3 -o ConnectTimeout=7 -o ConnectionAttempts=1 rjeczalik@99.999.999.999
```

So starting another kd process times out on trying to get access to metrics.bolt. Probably it should be more fine-grained. Related https://github.com/koding/koding/pull/11159.

**Comment by rjeczalik** [comment]
Also it would be useful if there's an option to disable metrics (e.g. if someone wants to disable them in development environment), like:

```
$ kd config set noMetrics true
$ sudo kd restart
```

**Comment by rjeczalik** [comment]
Already fixed.
