### ISSUE TITLE
Admin cannot access disabled user's stack.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9015]
## Current Behavior
![gif](http://g.recordit.co/0SREGlNBOG.gif)
http://recordit.co/0SREGlNBOG

After trying to fix the permissions, admin gets 'Something went wrong' error message displayed and disabled user's stack is not loaded as a result.

**Comment by diclee** [comment]
It fails when 'Stack Creation' is disabled for team members.

**Comment by alex-ionochkin** [comment]
Real server error is:
```
KiteError {message: "runtime error: invalid memory address or nil pointer dereference", name: "KiteError", type: "genericError", code: "", isOperational: true}
```
It happens when kloud's `addAdmin()` method is called - https://github.com/koding/koding/blob/master/client/app/lib/providers/computecontroller.coffee#L1128
Here is a call error stack of error in VM terminal:
```
goroutine 42975 [running]:
runtime/debug.Stack(0x40f40c, 0x1b7d840, 0xa568350b3f00)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
vendor/github.com/koding/kite.(*Client).runMethod.func1(0xc420a07f28, 0xc4204af400, 0xc420a07f30)
        /home/aionochkin/koding/go/src/vendor/github.com/koding/kite/request.go:68 +0x6e
panic(0x120e480, 0xc42000c0a0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
koding/kites/kloud/klient.(*Klient).AddUser(0x0, 0xc420a08b90, 0x4, 0x0, 0x0)
        /home/aionochkin/koding/go/src/koding/kites/kloud/klient/klient.go:262 +0x37
koding/kites/kloud/stack.(*Kloud).AdminAdd(0xc42018c420, 0xc420a44000, 0xc420ca7dc8, 0x4417eb, 0x0, 0x5368d9)
        /home/aionochkin/koding/go/src/koding/kites/kloud/stack/admin.go:28 +0x71
koding/kites/kloud/stack.(*Kloud).AdminAdd-fm(0xc420a44000, 0xc4204af470, 0xc4ffffffff, 0x0, 0xc4202dc1c0)
        /home/aionochkin/koding/go/src/koding/kites/kloud/kloud/kloud.go:345 +0x34
vendor/github.com/koding/kite.HandlerFunc.ServeKite(0xc420528930, 0xc420a44000, 0x0, 0x1b9fca8, 0x0, 0x0)
        /home/aionochkin/koding/go/src/vendor/github.com/koding/kite/method.go:40 +0x30
vendor/github.com/koding/kite.(*Method).ServeKite(0xc420165200, 0xc420a44000, 0x9, 0xc420150e70, 0xc420a44000, 0xc420b85820)
        /home/aionochkin/koding/go/src/vendor/github.com/koding/kite/method.go:236 +0x29f
vendor/github.com/koding/kite.(*Client).runMethod(0xc4204af400, 0xc420165200, 0xc420150e70)
        /home/aionochkin/koding/go/src/vendor/github.com/koding/kite/request.go:112 +0x174
created by vendor/github.com/koding/kite.(*Client).readLoop
        /home/aionochkin/koding/go/src/vendor/github.com/koding/kite/client.go:380 +0x13e
2016-09-14 16:58:47 [kloud] ERROR    runtime error: invalid memory address or nil pointer dereference (eb9f9d98ef0c46c1)
```

@rjeczalik, can you please take a look at this? ^^

**Comment by diclee** [comment]
Verify passed on sandbox.
