### ISSUE TITLE
Cannot find some modules in 'client' and 'client-landing' containers after docker-compose up

### ISSUE THREAD

**Issue by polzoom** [koding/koding#9392]
## Expected Behavior

After running:
docker-compose up -d
I should be able to visit localhost:8090

## Current Behavior

`docker-compose ps` says

```
....
koding_client-landing_1   scripts/bootstrap-containe ...   Exit 2
koding_client_1           scripts/bootstrap-containe ...   Exit 2
....
```

`docker-compose run --rm client-landing sh -c "cd node_modules && ls -al sax"` 
says me that i really dont have any 'sax' module in node_modules folder. The same situation with webpack and 'client' container. I tried to rm/add, restart these containers, nothing helped.

logs for koding_client-landing_1

```
Attaching to koding_client-landing_1
client-landing_1  | /opt/koding /opt/koding
client-landing_1  | make: Entering directory `/opt/koding/client/landing'
client-landing_1  | [15:10:31] Requiring external module coffee-script/register
client-landing_1  | [15:10:31] Warning: gulp version mismatch:
client-landing_1  | [15:10:31] Global gulp is 3.9.1
client-landing_1  | [15:10:31] Local gulp is 3.9.0
client-landing_1  | [15:10:31] Working directory changed to /opt/koding/client/landing/site.landing
client-landing_1  | 
client-landing_1  | module.js:340
client-landing_1  |     throw err;
client-landing_1  |     ^
client-landing_1  | Error: Cannot find module 'sax'
client-landing_1  |   at Function.Module._resolveFilename (module.js:338:15)
client-landing_1  |   at Function.Module._load (module.js:280:25)
client-landing_1  |   at Module.require (module.js:364:17)
client-landing_1  |   at require (module.js:380:17)
client-landing_1  |   at Object.<anonymous> (/opt/koding/client/node_modules/stylus/lib/functions/image.js:17:11)
client-landing_1  |   at Module._compile (module.js:456:26)
client-landing_1  |   at Object.Module._extensions..js (module.js:474:10)
client-landing_1  |   at Module.load (/opt/koding/client/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
...
client-landing_1  | make: *** [dev] Error 8
client-landing_1  | make: Leaving directory `/opt/koding/client/landing'
```

logs for client

```
Attaching to koding_client_1
client_1          | /opt/koding /opt/koding
client_1          | make: Entering directory `/opt/koding/client'
client_1          | /opt/koding/client/../scripts/check-node_modules.sh /opt/koding/client || /opt/koding/client/../scripts/install-npm.sh
client_1          | npm WARN cannot run in wd koding-client@0.1.0 ./.npm-preinstall.sh (wd=/opt/koding/client)
client_1          | 
client_1          | > weak@1.0.1 install /opt/koding/client/node_modules/@koding/bongo-client/node_modules/dnode/node_modules/weak
client_1          | > node-gyp rebuild
client_1          | 
client_1          | make[1]: Entering directory `/opt/koding/client/node_modules/@koding/bongo-client/node_modules/dnode/node_modules/weak/build'
client_1          |   CXX(target) Release/obj.target/weakref/src/weakref.o
client_1          |   SOLINK_MODULE(target) Release/obj.target/weakref.node
client_1          |   COPY Release/weakref.node
client_1          | make[1]: Leaving directory `/opt/koding/client/node_modules/@koding/bongo-client/node_modules/dnode/node_modules/weak/build'
client_1          | npm ERR! registry error parsing json
client_1          | npm WARN engine postcss@5.2.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.15.11"})
client_1          | npm WARN engine normalize-url@1.7.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.15.11"})
client_1          | npm WARN engine vendors@1.0.1: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.33","npm":"2.15.11"})
client_1          | npm WARN cannot run in wd koding-client@0.1.0 ./.npm-postinstall.sh (wd=/opt/koding/client)
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/kd.js requires lodash@'^3.6.0' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/lodash,
client_1          | npm WARN unmet dependency which is version 4.15.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/machina requires lodash@'~2.4.1' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/lodash,
client_1          | npm WARN unmet dependency which is version 4.15.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/react-router requires history@'^2.1.2' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/history,
client_1          | npm WARN unmet dependency which is version 3.0.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/react-select requires classnames@'^2.2.3' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/classnames,
client_1          | npm WARN unmet dependency which is version 2.1.3
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/nuclear-module/node_modules/nuclear-js requires immutable@'^3.8.1' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/immutable,
client_1          | npm WARN unmet dependency which is version 3.7.4
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/nightwatch/node_modules/mocha-nightwatch requires glob@'3.2.3' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/glob,
client_1          | npm WARN unmet dependency which is version 7.0.5
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-parser requires debug@'0.7.4' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/debug,
client_1          | npm WARN unmet dependency which is version 2.1.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires debug@'1.0.4' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-client/node_modules/debug,
client_1          | npm WARN unmet dependency which is version 0.7.4
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires parseuri@'0.0.4' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-client/node_modules/parseuri,
client_1          | npm WARN unmet dependency which is version 0.0.2
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/@kadira/storybook/node_modules/@kadira/storybook-ui requires keycode@'^2.1.1' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/keycode,
client_1          | npm WARN unmet dependency which is version 2.0.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/@kadira/storybook/node_modules/autoprefixer requires postcss@'^5.2.4' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/postcss,
client_1          | npm WARN unmet dependency which is version 5.1.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/@kadira/storybook/node_modules/express requires qs@'6.2.0' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/@kadira/storybook/node_modules/qs,
client_1          | npm WARN unmet dependency which is version 6.3.0
client_1          | broker-client@0.3.2 node_modules/broker-client
client_1          | └── hat@0.0.3
...
client_1          | /opt/koding/client/../scripts/check-node_modules.sh landing   || /opt/koding/client/../scripts/install-npm.sh -d landing
client_1          | /opt/koding/client/../run exec /opt/koding/client/../scripts/generate-bongo-schema --file /opt/koding/client/.schema.json
client_1          | Segment disabled because of missing configuration
client_1          | DataDog disabled because of missing configuration
client_1          | npm run watch:dev
client_1          | 
client_1          | > koding-client@0.1.0 watch:dev /opt/koding/client
client_1          | > NODE_ENV=development webpack --config webpack.config.coffee --colors --debug --watch
client_1          | 
client_1          | sh: 1: webpack: not found
client_1          | 
client_1          | npm ERR! Linux 3.19.0-61-generic
client_1          | npm ERR! argv "node" "/usr/local/bin/npm" "run" "watch:dev"
client_1          | npm ERR! node v0.10.33
client_1          | npm ERR! npm  v2.15.11
client_1          | npm ERR! file sh
client_1          | npm ERR! code ELIFECYCLE
client_1          | npm ERR! errno ENOENT
client_1          | npm ERR! syscall spawn
client_1          | npm ERR! koding-client@0.1.0 watch:dev: `NODE_ENV=development webpack --config webpack.config.coffee --colors --debug --watch`
client_1          | npm ERR! spawn ENOENT
client_1          | npm ERR! 
client_1          | npm ERR! Failed at the koding-client@0.1.0 watch:dev script 'NODE_ENV=development webpack --config webpack.config.coffee --colors --debug --watch'.
client_1          | npm ERR! This is most likely a problem with the koding-client package,
client_1          | npm ERR! not with npm itself.
client_1          | npm ERR! Tell the author that this fails on your system:
client_1          | npm ERR!     NODE_ENV=development webpack --config webpack.config.coffee --colors --debug --watch
client_1          | npm ERR! You can get information on how to open an issue for this project with:
client_1          | npm ERR!     npm bugs koding-client
client_1          | npm ERR! Or if that isn't available, you can get their info via:
client_1          | npm ERR! 
client_1          | npm ERR!     npm owner ls koding-client
client_1          | npm ERR! There is likely additional logging output above.
client_1          | 
client_1          | npm ERR! Please include the following file with any support request:
client_1          | npm ERR!     /opt/koding/client/npm-debug.log
client_1          | make: *** [watch-dev] Error 1
client_1          | make: Leaving directory `/opt/koding/client'
client_1          | /opt/koding /opt/koding
client_1          | make: Entering directory `/opt/koding/client'
client_1          | /opt/koding/client/../scripts/check-node_modules.sh /opt/koding/client || /opt/koding/client/../scripts/install-npm.sh
client_1          | npm WARN cannot run in wd koding-client@0.1.0 ./.npm-preinstall.sh (wd=/opt/koding/client)
client_1          | npm WARN engine postcss@5.2.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.15.11"})
client_1          | npm WARN engine normalize-url@1.7.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.15.11"})
client_1          | npm WARN engine vendors@1.0.1: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.33","npm":"2.15.11"})
client_1          | 
client_1          | > weak@1.0.1 install /opt/koding/client/node_modules/@koding/bongo-client/node_modules/dnode/node_modules/weak
client_1          | > node-gyp rebuild
client_1          | 
client_1          | make[1]: Entering directory `/opt/koding/client/node_modules/@koding/bongo-client/node_modules/dnode/node_modules/weak/build'
client_1          |   CXX(target) Release/obj.target/weakref/src/weakref.o
client_1          |   SOLINK_MODULE(target) Release/obj.target/weakref.node
client_1          |   COPY Release/weakref.node
client_1          | make[1]: Leaving directory `/opt/koding/client/node_modules/@koding/bongo-client/node_modules/dnode/node_modules/weak/build'
client_1          | npm WARN cannot run in wd koding-client@0.1.0 ./.npm-postinstall.sh (wd=/opt/koding/client)
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/kd.js requires lodash@'^3.6.0' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/lodash,
client_1          | npm WARN unmet dependency which is version 4.15.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/machina requires lodash@'~2.4.1' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/lodash,
client_1          | npm WARN unmet dependency which is version 4.15.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/react-router requires history@'^2.1.2' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/history,
client_1          | npm WARN unmet dependency which is version 3.0.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/react-select requires classnames@'^2.2.3' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/classnames,
client_1          | npm WARN unmet dependency which is version 2.1.3
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/nuclear-module/node_modules/nuclear-js requires immutable@'^3.8.1' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/immutable,
client_1          | npm WARN unmet dependency which is version 3.7.4
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/nightwatch/node_modules/mocha-nightwatch requires glob@'3.2.3' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/glob,
client_1          | npm WARN unmet dependency which is version 7.0.5
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-parser requires debug@'0.7.4' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/debug,
client_1          | npm WARN unmet dependency which is version 2.1.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires debug@'1.0.4' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-client/node_modules/debug,
client_1          | npm WARN unmet dependency which is version 0.7.4
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires parseuri@'0.0.4' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/socket.io/node_modules/socket.io-client/node_modules/parseuri,
client_1          | npm WARN unmet dependency which is version 0.0.2
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/@kadira/storybook/node_modules/@kadira/storybook-ui requires keycode@'^2.1.1' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/keycode,
client_1          | npm WARN unmet dependency which is version 2.0.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/@kadira/storybook/node_modules/autoprefixer requires postcss@'^5.2.4' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/postcss,
client_1          | npm WARN unmet dependency which is version 5.1.0
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/@kadira/storybook/node_modules/express requires qs@'6.2.0' but will load
client_1          | npm WARN unmet dependency /opt/koding/client/node_modules/@kadira/storybook/node_modules/qs,
client_1          | npm WARN unmet dependency which is version 6.3.0
client_1          | broker-client@0.3.2 node_modules/broker-client
client_1          | └── hat@0.0.3
....
client_1          | /opt/koding/client/../scripts/check-node_modules.sh landing   || /opt/koding/client/../scripts/install-npm.sh -d landing
client_1          | /opt/koding/client/../run exec /opt/koding/client/../scripts/generate-bongo-schema --file /opt/koding/client/.schema.json
client_1          | Segment disabled because of missing configuration
client_1          | DataDog disabled because of missing configuration
client_1          | npm run watch:dev
client_1          | 
client_1          | > koding-client@0.1.0 watch:dev /opt/koding/client
client_1          | > NODE_ENV=development webpack --config webpack.config.coffee --colors --debug --watch
client_1          | 
client_1          | sh: 1: webpack: not found
client_1          | 
client_1          | npm ERR! Linux 3.19.0-61-generic
client_1          | npm ERR! argv "node" "/usr/local/bin/npm" "run" "watch:dev"
client_1          | npm ERR! node v0.10.33
client_1          | npm ERR! npm  v2.15.11
client_1          | npm ERR! file sh
client_1          | npm ERR! code ELIFECYCLE
client_1          | npm ERR! errno ENOENT
client_1          | npm ERR! syscall spawn
client_1          | npm ERR! koding-client@0.1.0 watch:dev: `NODE_ENV=development webpack --config webpack.config.coffee --colors --debug --watch`
client_1          | npm ERR! spawn ENOENT
client_1          | npm ERR! 
client_1          | npm ERR! Failed at the koding-client@0.1.0 watch:dev script 'NODE_ENV=development webpack --config webpack.config.coffee --colors --debug --watch'.
client_1          | npm ERR! This is most likely a problem with the koding-client package,
client_1          | npm ERR! not with npm itself.
client_1          | npm ERR! Tell the author that this fails on your system:
client_1          | npm ERR!     NODE_ENV=development webpack --config webpack.config.coffee --colors --debug --watch
client_1          | npm ERR! You can get information on how to open an issue for this project with:
client_1          | npm ERR!     npm bugs koding-client
client_1          | npm ERR! Or if that isn't available, you can get their info via:
client_1          | npm ERR! 
client_1          | npm ERR!     npm owner ls koding-client
client_1          | npm ERR! There is likely additional logging output above.
client_1          | 
client_1          | npm ERR! Please include the following file with any support request:
client_1          | npm ERR!     /opt/koding/client/npm-debug.log
client_1          | make: *** [watch-dev] Error 1
client_1          | make: Leaving directory `/opt/koding/client'
```
## Your Environment

- Operation system : Ubuntu 14.04
- docker-compose version: 1.7.1

**Comment by szkl** [comment]
@polzoom did you execute `init` container like in snippet [here](https://github.com/koding/koding#start-developing)?
